export const products = [
  {
    id: "dsafjHGUVWJHBFJH",
    sellingPrice: "$150.99",
    profitMargin: "25%",
    stockLevel: 150,
    productCategory: "Electronics",
    shippingCost: "$10.50",
    shippingTime: "5 days",
    productDescription: "High quality and durable.",
    images: [
      "https://via.placeholder.com/150/0000FF/808080?text=Image1",
      "https://via.placeholder.com/150/FF0000/FFFFFF?text=Image2",
    ],
    barcode: "ABC-123456",
    supplierContact: "supplier1@example.com",
    variants: { Size: "M", Color: "Blue" },
    reviews: "4.5/5",
  },
  {
    id: "KJASGRWHEGREW",
    sellingPrice: "$85.75",
    profitMargin: "30%",
    stockLevel: 60,
    productCategory: "Clothing",
    shippingCost: "$7.20",
    shippingTime: "7 days",
    productDescription: "Limited edition item.",
    images: [
      "https://via.placeholder.com/150/008000/FFFFFF?text=Image3",
      "https://via.placeholder.com/150/FFFF00/000000?text=Image4",
    ],
    barcode: "ABC-654321",
    supplierContact: "supplier2@example.com",
    variants: { Size: "L", Color: "Green" },
    reviews: "4.7/5",
  },
  {
    id: "havsdjgdhsaf",
    sellingPrice: "$299.99",
    profitMargin: "40%",
    stockLevel: 30,
    productCategory: "Home Appliances",
    shippingCost: "$15.00",
    shippingTime: "10 days",
    productDescription: "Best seller in its category.",
    images: [
      "https://via.placeholder.com/150/FF4500/FFFFFF?text=Image5",
      "https://via.placeholder.com/150/1E90FF/FFFFFF?text=Image6",
    ],
    barcode: "ABC-789012",
    supplierContact: "supplier3@example.com",
    variants: { Size: "S", Color: "Red" },
    reviews: "4.8/5",
  },
  {
    id: "jhefwjdbafv",
    sellingPrice: "$45.50",
    profitMargin: "15%",
    stockLevel: 200,
    productCategory: "Books",
    shippingCost: "$5.00",
    shippingTime: "4 days",
    productDescription: "Newly released product.",
    images: [
      "https://via.placeholder.com/150/9400D3/FFFFFF?text=Image7",
      "https://via.placeholder.com/150/00CED1/FFFFFF?text=Image8",
    ],
    barcode: "ABC-345678",
    supplierContact: "supplier4@example.com",
    variants: { Size: "XL", Color: "Black" },
    reviews: "4.3/5",
  },
  {
    id: "adsfewjflbdh",
    sellingPrice: "$120.25",
    profitMargin: "35%",
    stockLevel: 80,
    productCategory: "Sports",
    shippingCost: "$8.75",
    shippingTime: "6 days",
    productDescription: "Customer favorite.",
    images: [
      "https://via.placeholder.com/150/FFD700/000000?text=Image9",
      "https://via.placeholder.com/150/00FF00/000000?text=Image10",
    ],
    barcode: "ABC-987654",
    supplierContact: "supplier5@example.com",
    variants: { Size: "M", Color: "Blue" },
    reviews: "4.6/5",
  },
  {
    id: "wfhvkewbyfve",
    sellingPrice: "$199.99",
    profitMargin: "45%",
    stockLevel: 120,
    productCategory: "Electronics",
    shippingCost: "$12.50",
    shippingTime: "9 days",
    productDescription: "High quality and durable.",
    images: [
      "https://via.placeholder.com/150/4B0082/FFFFFF?text=Image11",
      "https://via.placeholder.com/150/FF4500/FFFFFF?text=Image12",
    ],
    barcode: "ABC-223344",
    supplierContact: "supplier1@example.com",
    variants: { Size: "L", Color: "Green" },
    reviews: "4.9/5",
  },
  {
    id: "euhjfsauyvfhsdv",
    sellingPrice: "$60.00",
    profitMargin: "20%",
    stockLevel: 75,
    productCategory: "Clothing",
    shippingCost: "$6.00",
    shippingTime: "8 days",
    productDescription: "Limited edition item.",
    images: [
      "https://via.placeholder.com/150/000080/FFFFFF?text=Image13",
      "https://via.placeholder.com/150/FF6347/FFFFFF?text=Image14",
    ],
    barcode: "ABC-556677",
    supplierContact: "supplier2@example.com",
    variants: { Size: "S", Color: "Red" },
    reviews: "4.4/5",
  },
  {
    id: "wfuebjlfiuwbejnr",
    sellingPrice: "$275.49",
    profitMargin: "38%",
    stockLevel: 90,
    productCategory: "Home Appliances",
    shippingCost: "$14.50",
    shippingTime: "12 days",
    productDescription: "Best seller in its category.",
    images: [
      "https://via.placeholder.com/150/4682B4/FFFFFF?text=Image15",
      "https://via.placeholder.com/150/DC143C/FFFFFF?text=Image16",
    ],
    barcode: "ABC-889900",
    supplierContact: "supplier3@example.com",
    variants: { Size: "XL", Color: "Black" },
    reviews: "4.7/5",
  },
  {
    id: "fdoifwejiufb",
    sellingPrice: "$50.00",
    profitMargin: "18%",
    stockLevel: 180,
    productCategory: "Books",
    shippingCost: "$4.50",
    shippingTime: "3 days",
    productDescription: "Newly released product.",
    images: [
      "https://via.placeholder.com/150/20B2AA/FFFFFF?text=Image17",
      "https://via.placeholder.com/150/FF8C00/FFFFFF?text=Image18",
    ],
    barcode: "ABC-112233",
    supplierContact: "supplier4@example.com",
    variants: { Size: "M", Color: "Blue" },
    reviews: "4.5/5",
  },
  {
    id: "dsjgfehwlhfdasfa",
    sellingPrice: "$135.75",
    profitMargin: "33%",
    stockLevel: 110,
    productCategory: "Sports",
    shippingCost: "$9.25",
    shippingTime: "7 days",
    productDescription: "Customer favorite.",
    images: [
      "https://via.placeholder.com/150/FF4500/FFFFFF?text=Image19",
      "https://via.placeholder.com/150/9400D3/FFFFFF?text=Image20",
    ],
    barcode: "ABC-445566",
    supplierContact: "supplier5@example.com",
    variants: { Size: "L", Color: "Green" },
    reviews: "4.8/5",
  },
  {
    id: "lejavjkdsbk",
    sellingPrice: "$210.00",
    profitMargin: "42%",
    stockLevel: 140,
    productCategory: "Electronics",
    shippingCost: "$11.00",
    shippingTime: "10 days",
    productDescription: "High quality and durable.",
    images: [
      "https://via.placeholder.com/150/0000FF/FFFFFF?text=Image21",
      "https://via.placeholder.com/150/FFD700/FFFFFF?text=Image22",
    ],
    barcode: "ABC-778899",
    supplierContact: "supplier1@example.com",
    variants: { Size: "XL", Color: "Black" },
    reviews: "4.9/5",
  },
  {
    id: "yuhjdflakshb",
    sellingPrice: "$70.25",
    profitMargin: "22%",
    stockLevel: 65,
    productCategory: "Clothing",
    shippingCost: "$7.50",
    shippingTime: "6 days",
    productDescription: "Limited edition item.",
    images: [
      "https://via.placeholder.com/150/FF0000/FFFFFF?text=Image23",
      "https://via.placeholder.com/150/0000CD/FFFFFF?text=Image24",
    ],
    barcode: "ABC-990011",
    supplierContact: "supplier2@example.com",
    variants: { Size: "S", Color: "Red" },
    reviews: "4.6/5",
  },
  {
    id: "ieuagnkljfakJ",
    sellingPrice: "$285.00",
    profitMargin: "44%",
    stockLevel: 95,
    productCategory: "Home Appliances",
    shippingCost: "$13.75",
    shippingTime: "11 days",
    productDescription: "Best seller in its category.",
    images: [
      "https://via.placeholder.com/150/00CED1/FFFFFF?text=Image25",
      "https://via.placeholder.com/150/FF4500/FFFFFF?text=Image26",
    ],
    barcode: "ABC-223344",
    supplierContact: "supplier3@example.com",
    variants: { Size: "L", Color: "Green" },
    reviews: "4.8/5",
  },
  {
    id: "kjfvbgwhgjnjh",
    sellingPrice: "$55.50",
    profitMargin: "16%",
    stockLevel: 175,
    productCategory: "Books",
    shippingCost: "$5.50",
    shippingTime: "4 days",
    productDescription: "Newly released product.",
    images: [
      "https://via.placeholder.com/150/FF8C00/FFFFFF?text=Image27",
      "https://via.placeholder.com/150/9400D3/FFFFFF?text=Image28",
    ],
    barcode: "ABC-556677",
    supplierContact: "supplier4@example.com",
    variants: { Size: "XL", Color: "Black" },
    reviews: "4.3/5",
  },
  {
    id: "uykewhbgfrhtgwj",
    sellingPrice: "$145.25",
    profitMargin: "36%",
    stockLevel: 85,
    productCategory: "Sports",
    shippingCost: "$8.00",
    shippingTime: "7 days",
    productDescription: "Customer favorite.",
    images: [
      "https://via.placeholder.com/150/4682B4/FFFFFF?text=Image29",
      "https://via.placeholder.com/150/DC143C/FFFFFF?text=Image30",
    ],
    barcode: "ABC-778899",
    supplierContact: "supplier5@example.com",
    variants: { Size: "M", Color: "Blue" },
    reviews: "4.7/5",
  },
  {
    id: "rbeqkqhgtgehbkbgu",
    sellingPrice: "$230.50",
    profitMargin: "47%",
    stockLevel: 130,
    productCategory: "Electronics",
    shippingCost: "$11.50",
    shippingTime: "9 days",
    productDescription: "High quality and durable.",
    images: [
      "https://via.placeholder.com/150/FFD700/FFFFFF?text=Image31",
      "https://via.placeholder.com/150/4B0082/FFFFFF?text=Image32",
    ],
    barcode: "ABC-334455",
    supplierContact: "supplier1@example.com",
    variants: { Size: "XL", Color: "Black" },
    reviews: "4.9/5",
  },
  {
    id: "ulgniuhuerwwn",
    sellingPrice: "$80.00",
    profitMargin: "28%",
    stockLevel: 70,
    productCategory: "Clothing",
    shippingCost: "$7.00",
    shippingTime: "5 days",
    productDescription: "Limited edition item.",
    images: [
      "https://via.placeholder.com/150/1E90FF/FFFFFF?text=Image33",
      "https://via.placeholder.com/150/FF6347/FFFFFF?text=Image34",
    ],
    barcode: "ABC-667788",
    supplierContact: "supplier2@example.com",
    variants: { Size: "S", Color: "Red" },
    reviews: "4.5/5",
  },
  {
    id: "fsugfbetuhir",
    sellingPrice: "$265.75",
    profitMargin: "43%",
    stockLevel: 100,
    productCategory: "Home Appliances",
    shippingCost: "$14.00",
    shippingTime: "12 days",
    productDescription: "Best seller in its category.",
    images: [
      "https://via.placeholder.com/150/00FF00/FFFFFF?text=Image35",
      "https://via.placeholder.com/150/FF4500/FFFFFF?text=Image36",
    ],
    barcode: "ABC-990011",
    supplierContact: "supplier3@example.com",
    variants: { Size: "L", Color: "Green" },
    reviews: "4.8/5",
  },
  {
    id: "qfuhebgtuer",
    sellingPrice: "$65.00",
    profitMargin: "19%",
    stockLevel: 160,
    productCategory: "Books",
    shippingCost: "$6.00",
    shippingTime: "4 days",
    productDescription: "Newly released product.",
    images: [
      "https://via.placeholder.com/150/FF4500/FFFFFF?text=Image37",
      "https://via.placeholder.com/150/9400D3/FFFFFF?text=Image38",
    ],
    barcode: "ABC-334455",
    supplierContact: "supplier4@example.com",
    variants: { Size: "XL", Color: "Black" },
    reviews: "4.3/5",
  },
  {
    id: "itguejnlthkjuniub",
    sellingPrice: "$160.99",
    profitMargin: "39%",
    stockLevel: 95,
    productCategory: "Sports",
    shippingCost: "$9.50",
    shippingTime: "8 days",
    productDescription: "Customer favorite.",
    images: [
      "https://via.placeholder.com/150/FFD700/FFFFFF?text=Image39",
      "https://via.placeholder.com/150/4B0082/FFFFFF?text=Image40",
    ],
    barcode: "ABC-112233",
    supplierContact: "supplier5@example.com",
    variants: { Size: "M", Color: "Blue" },
    reviews: "4.6/5",
  },
];
