export const products = [
  {
    id: "dsafjHGUVWJHBFJH",
    sellingPrice: "$150.99",
    profitMargin: "25%",
    stockLevel: 150,
    productCategory: "Electronics",
    shippingCost: "$10.50",
    shippingTime: "5 days",
    productDescription: "High quality and durable.",
    images: [
      "https://res.cloudinary.com/drfqge33t/image/upload/v1723279914/29shoes_4_jestc6.jpg",
      "https://res.cloudinary.com/drfqge33t/image/upload/v1723279914/29shoes_4_jestc6.jpg",
    ],
    barcode: "ABC-123456",
    supplierContact: "supplier1@example.com",
    variants: { Size: "M", Color: "Blue" },
    reviews: "4.5/5",
  },
  {
    id: "KJASGRWHEGREW",
    sellingPrice: "$85.75",
    profitMargin: "30%",
    stockLevel: 60,
    productCategory: "Clothing",
    shippingCost: "$7.20",
    shippingTime: "7 days",
    productDescription: "Limited edition item.",
    images: [
      "https://res.cloudinary.com/drfqge33t/image/upload/v1723279914/29shoes_4_jestc6.jpg",
      "https://res.cloudinary.com/drfqge33t/image/upload/v1723279914/29shoes_4_jestc6.jpg",
    ],
    barcode: "ABC-654321",
    supplierContact: "supplier2@example.com",
    variants: { Size: "L", Color: "Green" },
    reviews: "4.7/5",
  },
  {
    id: "havsdjgdhsaf",
    sellingPrice: "$299.99",
    profitMargin: "40%",
    stockLevel: 30,
    productCategory: "Home Appliances",
    shippingCost: "$15.00",
    shippingTime: "10 days",
    productDescription: "Best seller in its category.",
    images: [
      "https://res.cloudinary.com/drfqge33t/image/upload/v1723279914/29shoes_4_jestc6.jpg",
      "https://res.cloudinary.com/drfqge33t/image/upload/v1723279914/29shoes_4_jestc6.jpg",
    ],
    barcode: "ABC-789012",
    supplierContact: "supplier3@example.com",
    variants: { Size: "S", Color: "Red" },
    reviews: "4.8/5",
  },
  {
    id: "jhefwjdbafv",
    sellingPrice: "$45.50",
    profitMargin: "15%",
    stockLevel: 200,
    productCategory: "Books",
    shippingCost: "$5.00",
    shippingTime: "4 days",
    productDescription: "Newly released product.",
    images: [
      "https://res.cloudinary.com/drfqge33t/image/upload/v1723279914/29shoes_4_jestc6.jpg",
      "https://res.cloudinary.com/drfqge33t/image/upload/v1723279914/29shoes_4_jestc6.jpg",
    ],
    barcode: "ABC-345678",
    supplierContact: "supplier4@example.com",
    variants: { Size: "XL", Color: "Black" },
    reviews: "4.3/5",
  },
  {
    id: "adsfewjflbdh",
    sellingPrice: "$120.25",
    profitMargin: "35%",
    stockLevel: 80,
    productCategory: "Sports",
    shippingCost: "$8.75",
    shippingTime: "6 days",
    productDescription: "Customer favorite.",
    images: [
      "https://res.cloudinary.com/drfqge33t/image/upload/v1723279914/29shoes_4_jestc6.jpg",
      "https://res.cloudinary.com/drfqge33t/image/upload/v1723279914/29shoes_4_jestc6.jpg",
    ],
    barcode: "ABC-987654",
    supplierContact: "supplier5@example.com",
    variants: { Size: "M", Color: "Blue" },
    reviews: "4.6/5",
  },
  {
    id: "wfhvkewbyfve",
    sellingPrice: "$199.99",
    profitMargin: "45%",
    stockLevel: 120,
    productCategory: "Electronics",
    shippingCost: "$12.50",
    shippingTime: "9 days",
    productDescription: "High quality and durable.",
    images: [
      "https://res.cloudinary.com/drfqge33t/image/upload/v1723279914/29shoes_4_jestc6.jpg",
      "https://res.cloudinary.com/drfqge33t/image/upload/v1723279914/29shoes_4_jestc6.jpg",
    ],
    barcode: "ABC-223344",
    supplierContact: "supplier1@example.com",
    variants: { Size: "L", Color: "Green" },
    reviews: "4.9/5",
  },
  {
    id: "euhjfsauyvfhsdv",
    sellingPrice: "$60.00",
    profitMargin: "20%",
    stockLevel: 75,
    productCategory: "Clothing",
    shippingCost: "$6.00",
    shippingTime: "8 days",
    productDescription: "Limited edition item.",
    images: [
      "https://res.cloudinary.com/drfqge33t/image/upload/v1723279914/29shoes_4_jestc6.jpg",
      "https://res.cloudinary.com/drfqge33t/image/upload/v1723279914/29shoes_4_jestc6.jpg",
    ],
    barcode: "ABC-556677",
    supplierContact: "supplier2@example.com",
    variants: { Size: "S", Color: "Red" },
    reviews: "4.4/5",
  },
  {
    id: "wfuebjlfiuwbejnr",
    sellingPrice: "$275.49",
    profitMargin: "38%",
    stockLevel: 90,
    productCategory: "Home Appliances",
    shippingCost: "$14.50",
    shippingTime: "12 days",
    productDescription: "Best seller in its category.",
    images: [
      "https://res.cloudinary.com/drfqge33t/image/upload/v1723279914/29shoes_4_jestc6.jpg",
      "https://res.cloudinary.com/drfqge33t/image/upload/v1723279914/29shoes_4_jestc6.jpg",
    ],
    barcode: "ABC-889900",
    supplierContact: "supplier3@example.com",
    variants: { Size: "XL", Color: "Black" },
    reviews: "4.7/5",
  },
  {
    id: "fdoifwejiufb",
    sellingPrice: "$50.00",
    profitMargin: "18%",
    stockLevel: 180,
    productCategory: "Books",
    shippingCost: "$4.50",
    shippingTime: "3 days",
    productDescription: "Newly released product.",
    images: [
      "https://res.cloudinary.com/drfqge33t/image/upload/v1723279914/29shoes_4_jestc6.jpg",
      "https://res.cloudinary.com/drfqge33t/image/upload/v1723279914/29shoes_4_jestc6.jpg",
    ],
    barcode: "ABC-112233",
    supplierContact: "supplier4@example.com",
    variants: { Size: "M", Color: "Blue" },
    reviews: "4.5/5",
  },
  {
    id: "dsjgfehwlhfdasfa",
    sellingPrice: "$135.75",
    profitMargin: "33%",
    stockLevel: 110,
    productCategory: "Sports",
    shippingCost: "$9.25",
    shippingTime: "7 days",
    productDescription: "Customer favorite.",
    images: [
      "https://res.cloudinary.com/drfqge33t/image/upload/v1723279914/29shoes_4_jestc6.jpg",
      "https://res.cloudinary.com/drfqge33t/image/upload/v1723279914/29shoes_4_jestc6.jpg",
    ],
    barcode: "ABC-445566",
    supplierContact: "supplier5@example.com",
    variants: { Size: "L", Color: "Green" },
    reviews: "4.8/5",
  },
  {
    id: "lejavjkdsbk",
    sellingPrice: "$210.00",
    profitMargin: "42%",
    stockLevel: 140,
    productCategory: "Electronics",
    shippingCost: "$11.00",
    shippingTime: "10 days",
    productDescription: "High quality and durable.",
    images: [
      "https://res.cloudinary.com/drfqge33t/image/upload/v1723279914/29shoes_4_jestc6.jpg",
      "https://res.cloudinary.com/drfqge33t/image/upload/v1723279914/29shoes_4_jestc6.jpg",
    ],
    barcode: "ABC-778899",
    supplierContact: "supplier1@example.com",
    variants: { Size: "XL", Color: "Black" },
    reviews: "4.9/5",
  },
  {
    id: "yuhjdflakshb",
    sellingPrice: "$70.25",
    profitMargin: "22%",
    stockLevel: 65,
    productCategory: "Clothing",
    shippingCost: "$7.50",
    shippingTime: "6 days",
    productDescription: "Limited edition item.",
    images: [
      "https://res.cloudinary.com/drfqge33t/image/upload/v1723279914/29shoes_4_jestc6.jpg",
      "https://res.cloudinary.com/drfqge33t/image/upload/v1723279914/29shoes_4_jestc6.jpg",
    ],
    barcode: "ABC-990011",
    supplierContact: "supplier2@example.com",
    variants: { Size: "S", Color: "Red" },
    reviews: "4.6/5",
  },
  {
    id: "ieuagnkljfakJ",
    sellingPrice: "$285.00",
    profitMargin: "44%",
    stockLevel: 95,
    productCategory: "Home Appliances",
    shippingCost: "$13.75",
    shippingTime: "11 days",
    productDescription: "Best seller in its category.",
    images: [
      "https://res.cloudinary.com/drfqge33t/image/upload/v1723279914/29shoes_4_jestc6.jpg",
      "https://res.cloudinary.com/drfqge33t/image/upload/v1723279914/29shoes_4_jestc6.jpg",
    ],
    barcode: "ABC-223344",
    supplierContact: "supplier3@example.com",
    variants: { Size: "L", Color: "Green" },
    reviews: "4.8/5",
  },
  {
    id: "kjfvbgwhgjnjh",
    sellingPrice: "$55.50",
    profitMargin: "16%",
    stockLevel: 175,
    productCategory: "Books",
    shippingCost: "$5.50",
    shippingTime: "4 days",
    productDescription: "Newly released product.",
    images: [
      "https://res.cloudinary.com/drfqge33t/image/upload/v1723279914/29shoes_4_jestc6.jpg",
      "https://res.cloudinary.com/drfqge33t/image/upload/v1723279914/29shoes_4_jestc6.jpg",
    ],
    barcode: "ABC-556677",
    supplierContact: "supplier4@example.com",
    variants: { Size: "XL", Color: "Black" },
    reviews: "4.3/5",
  },
  {
    id: "uykewhbgfrhtgwj",
    sellingPrice: "$145.25",
    profitMargin: "36%",
    stockLevel: 85,
    productCategory: "Sports",
    shippingCost: "$8.00",
    shippingTime: "7 days",
    productDescription: "Customer favorite.",
    images: [
      "https://res.cloudinary.com/drfqge33t/image/upload/v1723279914/29shoes_4_jestc6.jpg",
      "https://res.cloudinary.com/drfqge33t/image/upload/v1723279914/29shoes_4_jestc6.jpg",
    ],
    barcode: "ABC-778899",
    supplierContact: "supplier5@example.com",
    variants: { Size: "M", Color: "Blue" },
    reviews: "4.7/5",
  },
  {
    id: "rbeqkqhgtgehbkbgu",
    sellingPrice: "$230.50",
    profitMargin: "47%",
    stockLevel: 130,
    productCategory: "Electronics",
    shippingCost: "$11.50",
    shippingTime: "9 days",
    productDescription: "High quality and durable.",
    images: [
      "https://res.cloudinary.com/drfqge33t/image/upload/v1723279914/29shoes_4_jestc6.jpg",
      "https://res.cloudinary.com/drfqge33t/image/upload/v1723279914/29shoes_4_jestc6.jpg",
    ],
    barcode: "ABC-334455",
    supplierContact: "supplier1@example.com",
    variants: { Size: "XL", Color: "Black" },
    reviews: "4.9/5",
  },
  {
    id: "ulgniuhuerwwn",
    sellingPrice: "$80.00",
    profitMargin: "28%",
    stockLevel: 70,
    productCategory: "Clothing",
    shippingCost: "$7.00",
    shippingTime: "5 days",
    productDescription: "Limited edition item.",
    images: [
      "https://res.cloudinary.com/drfqge33t/image/upload/v1723279914/29shoes_4_jestc6.jpg",
      "https://res.cloudinary.com/drfqge33t/image/upload/v1723279914/29shoes_4_jestc6.jpg",
    ],
    barcode: "ABC-667788",
    supplierContact: "supplier2@example.com",
    variants: { Size: "S", Color: "Red" },
    reviews: "4.5/5",
  },
  {
    id: "fsugfbetuhir",
    sellingPrice: "$265.75",
    profitMargin: "43%",
    stockLevel: 100,
    productCategory: "Home Appliances",
    shippingCost: "$14.00",
    shippingTime: "12 days",
    productDescription: "Best seller in its category.",
    images: [
      "https://res.cloudinary.com/drfqge33t/image/upload/v1723279914/29shoes_4_jestc6.jpg",
      "https://res.cloudinary.com/drfqge33t/image/upload/v1723279914/29shoes_4_jestc6.jpg",
    ],
    barcode: "ABC-990011",
    supplierContact: "supplier3@example.com",
    variants: { Size: "L", Color: "Green" },
    reviews: "4.8/5",
  },
  {
    id: "qfuhebgtuer",
    sellingPrice: "$65.00",
    profitMargin: "19%",
    stockLevel: 160,
    productCategory: "Books",
    shippingCost: "$6.00",
    shippingTime: "4 days",
    productDescription: "Newly released product.",
    images: [
      "https://res.cloudinary.com/drfqge33t/image/upload/v1723279914/29shoes_4_jestc6.jpg",
      "https://res.cloudinary.com/drfqge33t/image/upload/v1723279914/29shoes_4_jestc6.jpg",
    ],
    barcode: "ABC-334455",
    supplierContact: "supplier4@example.com",
    variants: { Size: "XL", Color: "Black" },
    reviews: "4.3/5",
  },
  {
    id: "itguejnlthkjuniub",
    sellingPrice: "$160.99",
    profitMargin: "39%",
    stockLevel: 95,
    productCategory: "Sports",
    shippingCost: "$9.50",
    shippingTime: "8 days",
    productDescription: "Customer favorite.",
    images: [
      "https://res.cloudinary.com/drfqge33t/image/upload/v1723279914/29shoes_4_jestc6.jpg",
      "https://res.cloudinary.com/drfqge33t/image/upload/v1723279914/29shoes_4_jestc6.jpg",
    ],
    barcode: "ABC-112233",
    supplierContact: "supplier5@example.com",
    variants: { Size: "M", Color: "Blue" },
    reviews: "4.6/5",
  },
];
