export const users = [
  {
    id: 1,
    name: "John Doe",
    houseAddress: "123 Maple Street, Springfield, IL",
    amountOrders: 12,
    emailAddress: "johndoe@example.com",
    phoneNumber: "+1-555-123-4567",
  },
  {
    id: 2,
    name: "Jane Smith",
    houseAddress: "456 Oak Avenue, Dallas, TX",
    amountOrders: 19,
    emailAddress: "janesmith@example.com",
    phoneNumber: "+1-555-234-5678",
  },
  {
    id: 3,
    name: "Mike Johnson",
    houseAddress: "789 Pine Road, Miami, FL",
    amountOrders: 50,
    emailAddress: "mikejohnson@example.com",
    phoneNumber: "+1-555-345-6789",
  },
  {
    id: 4,
    name: "Emily Davis",
    houseAddress: "101 Birch Lane, Seattle, WA",
    amountOrders: 10,
    emailAddress: "emilydavis@example.com",
    phoneNumber: "+1-555-456-7890",
  },
  {
    id: 5,
    name: "David Brown",
    houseAddress: "202 Cedar Drive, Boston, MA",
    amountOrders: 21,
    emailAddress: "davidbrown@example.com",
    phoneNumber: "+1-555-567-8901",
  },
  {
    id: 6,
    name: "Sophia Wilson",
    houseAddress: "303 Elm Court, San Francisco, CA",
    amountOrders: 19,
    emailAddress: "sophiawilson@example.com",
    phoneNumber: "+1-555-678-9012",
  },
  {
    id: 7,
    name: "James Anderson",
    houseAddress: "404 Willow Boulevard, New York, NY",
    amountOrders: 22,
    emailAddress: "jamesanderson@example.com",
    phoneNumber: "+1-555-789-0123",
  },
  {
    id: 8,
    name: "Olivia Martinez",
    houseAddress: "505 Redwood Terrace, Chicago, IL",
    amountOrders: 31,
    emailAddress: "oliviamartinez@example.com",
    phoneNumber: "+1-555-890-1234",
  },
  {
    id: 9,
    name: "Liam Thompson",
    houseAddress: "606 Ash Street, Los Angeles, CA",
    amountOrders: 201,
    emailAddress: "liamthompson@example.com",
    phoneNumber: "+1-555-901-2345",
  },
  {
    id: 10,
    name: "Emma Garcia",
    houseAddress: "707 Spruce Circle, Denver, CO",
    amountOrders: 207,
    emailAddress: "emmagarcia@example.com",
    phoneNumber: "+1-555-012-3456",
  },
];
