export const ecommerce_integration_list = [
  {
    image: "/woocommerce.png",
    title: "WooCommerce Integration",
    body: "Synchronize your InvenMatrix account with your WooCommerce store to streamline your inventory, manage orders, and update product information with ease.",
    id: 1,
    status: false,
  },
  {
    image: "/shopify.png",
    title: "Shopify Integration",
    body: "Connect your InvenMatrix profile with your Shopify store to automate inventory updates, track orders in real-time, and simplify product management.",
    id: 2,
    status: true,
  },
  {
    image: "/amazon.png",
    title: "Amazon Integration",
    body: "Link your InvenMatrix account to your Amazon seller profile for centralized inventory management, efficient order tracking, and better control over your listings.",
    id: 3,
    status: true,
  },
  {
    image: "/magneto.png",
    title: "Magento Integration",
    body: "Integrate your InvenMatrix profile with your Magento store for seamless inventory control, order management, and synchronized product data.",
    id: 4,
    status: false,
  },
  {
    image: "/bigcommerce.png",
    title: "BigCommerce Integration",
    body: "Connect with BigCommerce to manage your store effortlessly. Sync your inventory, keep track of orders, and ensure accurate product details with ease.",
    id: 5,
    status: false,
  },
  {
    image: "/square.png",
    title: "Square Integration",
    body: "Synchronize your InvenMatrix profile with Square to streamline product management, monitor inventory levels, and maintain real-time order tracking.",
    id: 6,
    status: true,
  },
  {
    image: "/ebay.png",
    title: "eBay Integration",
    body: "Connect your InvenMatrix account with eBay to simplify inventory management, order processing, and ensure your product listings are always up to date.",
    id: 7,
    status: false,
  },
  {
    image: "/etsy.png",
    title: "Etsy Integration",
    body: "Integrate your InvenMatrix profile with Etsy to keep your handmade and vintage items organized, manage orders effectively, and keep track of your stock.",
    id: 8,
    status: true,
  },
  {
    image: "/wix.png",
    title: "Wix Integration",
    body: "Connect InvenMatrix with your Wix store to synchronize inventory, track orders seamlessly, and manage product data efficiently.",
    id: 9,
    status: true,
  },
  {
    image: "/wix.png",
    title: "Wix Integration",
    body: "Connect InvenMatrix with your Wix store to synchronize inventory, track orders seamlessly, and manage product data efficiently.",
    id: 9,
    status: true,
  },
  {
    image: "/wix.png",
    title: "Wix Integration",
    body: "Connect InvenMatrix with your Wix store to synchronize inventory, track orders seamlessly, and manage product data efficiently.",
    id: 9,
    status: true,
  },
];
export const ecommerce_completed_integration_list = [
  {
    image: "/shopify.png",
    title: "Shopify Integration",
    body: "Connect your InvenMatrix profile with your Shopify store to automate inventory updates, track orders in real-time, and simplify product management.",
    id: 2,
    status: true,
  },
  {
    image: "/amazon.png",
    title: "Amazon Integration",
    body: "Link your InvenMatrix account to your Amazon seller profile for centralized inventory management, efficient order tracking, and better control over your listings.",
    id: 3,
    status: true,
  },

  {
    image: "/square.png",
    title: "Square Integration",
    body: "Synchronize your InvenMatrix profile with Square to streamline product management, monitor inventory levels, and maintain real-time order tracking.",
    id: 6,
    status: true,
  },
  {
    image: "/etsy.png",
    title: "Etsy Integration",
    body: "Integrate your InvenMatrix profile with Etsy to keep your handmade and vintage items organized, manage orders effectively, and keep track of your stock.",
    id: 8,
    status: true,
  },
  {
    image: "/wix.png",
    title: "Wix Integration",
    body: "Connect InvenMatrix with your Wix store to synchronize inventory, track orders seamlessly, and manage product data efficiently.",
    id: 9,
    status: true,
  },
];
